// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbUJye6SP1uOVTHIPP4gY6mW0l1tCAKBs',
    appId: '1:575316044423:web:7d47f2501f3c60c71fe622',
    messagingSenderId: '575316044423',
    projectId: 'dam-u4-proyecto1-19400586',
    authDomain: 'dam-u4-proyecto1-19400586.firebaseapp.com',
    storageBucket: 'dam-u4-proyecto1-19400586.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZV5HuJ5EIeazbSFX8ot4L55E8tPFayAM',
    appId: '1:575316044423:android:e95571bd11706e4b1fe622',
    messagingSenderId: '575316044423',
    projectId: 'dam-u4-proyecto1-19400586',
    storageBucket: 'dam-u4-proyecto1-19400586.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp97JUf_63GBaopOsysFuSYxgtT2i1CbE',
    appId: '1:575316044423:ios:8e3bb9e2c6445b041fe622',
    messagingSenderId: '575316044423',
    projectId: 'dam-u4-proyecto1-19400586',
    storageBucket: 'dam-u4-proyecto1-19400586.appspot.com',
    iosClientId: '575316044423-6lhuafilr3igdv36s9d6ccrsn1ao3r40.apps.googleusercontent.com',
    iosBundleId: 'com.example.damU4Proyecto119400586',
  );
}
